####################################
# Adresse IP de l'interface  KNX/IP#
####################################

# capteurs binaires#
binary_sensor:
  #alimentation KNX
  - name: "Alarme dépasement Température"
    state_address: "0/1/0"
  - name: "Alarme dépasement Courant"
    state_address: "0/1/1"
  - name: "Alarme tension trop basse"
    state_address: "0/1/2"
  - name: "Alarme Trafic BUS"
    state_address: "0/1/3"
  #Capteur alarme
  - name: "capteur cuisine"
    state_address: "12/7/0"
  - name: "capteur salon piano"
    state_address: "12/7/1"
  - name: "capteur porche"
    state_address: "12/7/2"
  - name: "capteur Patio"
    state_address: "12/7/4"
  - name: "capteur Garage"
    state_address: "12/7/6"
  - name: "capteur couloir étage"
    state_address: "12/7/5"
  #Capteur Chaudiere
  - name: "Etat flamme chaudiere"
    state_address: "17/0/7"
  - name: "Etat H1"
    state_address: "17/0/4"
  - name: "Etat H2"
    state_address: "17/0/1"
  - name: "Etat ECS"
    state_address: "17/0/11"
  - name: "Etat Marche arret H1"
    state_address: "17/1/0"
  - name: "Etat Marche Arret H2"
    state_address: "17/1/2"
  - name: "Etat Marche arret ECS"
    state_address: "17/1/3"
  - name: "Etat Marche arret Mode été"
    state_address: "17/1/1"
  - name: "blocage Circulateur radiateur étage"
    state_address: "17/3/4"

  # Capteurs Volets
  - name: "Volet Buanderie position basse"
    state_address: "2/0/4"
  - name: "Volet Buanderie position haute"
    state_address: "2/0/5"
  - name: "Volet Salle de bain position basse"
    state_address: "2/1/4"
  - name: "Volet Salle de bain position haute"
    state_address: "2/1/5"
  - name: "Volet Sallon télé position basse"
    state_address: "2/2/4"
  - name: "Volet Sallon télé position haute"
    state_address: "2/2/5"
  - name: "Volet Chambre Margaux position basse"
    state_address: "2/3/4"
  - name: "Volet Chambre Margaux position haute"
    state_address: "2/3/5"
  - name: "Volet Chambre Auguste position basse"
    state_address: "2/4/4"
  - name: "Volet Chambre Auguste position haute"
    state_address: "2/4/5"
  - name: "Volet Bureau position basse"
    state_address: "2/5/4"
  - name: "Volet Bureau position haute"
    state_address: "2/5/5"
  - name: "Volet Salle d'eau position basse"
    state_address: "2/6/4"
  - name: "Volet Salle d'eau position haute"
    state_address: "2/6/5"
  - name: "Volet Chambre Parental position basse"
    state_address: "2/7/4"
  - name: "Volet Chambre Parental position haute"
    state_address: "2/7/5"

    # diag actionneur Ruban LED
  - name: "Valeur Cuorant dépassée"
    state_address: "1/2/9"
  - name: "Température élevée"
    state_address: "1/2/11"
  - name: "Etat alimentation 24V"
    state_address: "1/2/12"
  - name: "Etat Jour=1/nuit=0 "
    state_address: "1/2/10"
  - name: "dépassement température mur chauffant"
    state_address: "11/1/8"
  - name: "detection chan 1"
    state_address: "12/5/2"

  #thermostat
  - name: "actionneur de chauffe Salle d'eau"
    state_address: "7/1/2"
  - name: "Etat chauffage salle d'eau"
    state_address: "12/4/1"
  - name: "actionneur de chauffe mur chauffant"
    state_address: "11/1/2"
  - name: "Etat chauffage mur chauffant"
    state_address: "12/4/2"
  - name: "Etat vannne chambre Parents"
    state_address: "17/3/7"
  - name: "Etat vannne chambre Margaux"
    state_address: "17/3/3"
  - name: "Etat vannne chambre Auguste"
    state_address: "17/3/5"
  - name: "Etat vannne chambre Ami"
    state_address: "17/3/1"

#Lumières
light:
  # lumière tout ou rien
  - name: "Cuisine"
    address: "4/3/0"
    state_address: "4/3/1"
  - name: "Luminaire Ilot"
    address: "6/5/1"
    state_address: "6/5/2"
  - name: "Cellier"
    address: "4/4/0"
    state_address: "4/4/1"
  - name: "Terrasse extérieure"
    address: "4/6/0"
    state_address: "4/6/1"
  - name: "Eclairage jardin"
    address: "18/0/0"
    state_address: "18/0/1"
  - name: "Porsche et travées"
    address: "4/5/0"
    state_address: "4/5/1"
  - name: "Buanderie"
    address: "1/6/0"
    state_address: "1/6/1"
  - name: "Bureau"
    address: "1/4/0"
    state_address: "1/4/1"
  - name: "Entrée couloir"
    address: "1/7/0"
    state_address: "1/7/1"
  - name: "WC RDC"
    address: "1/5/0"
    state_address: "1/5/1"
  - name: "Salle d'eau"
    address: "5/1/0"
    state_address: "5/1/1"
  - name: "Chambre Margaux"
    address: "5/4/0"
    state_address: "5/4/1"
  - name: "Dressing"
    address: "5/2/0"
    state_address: "5/2/1"
  - name: "Prise commandée Salon Télé"
    address: "13/0/1"
    state_address: "13/0/2"

  - name: "WC étage"
    address: "5/6/0"
    state_address: "5/6/1"
  - name: "Chambre d'amis"
    address: "5/7/0"
    state_address: "5/7/1"
  - name: "Couloir étage"
    address: "5/0/0"
    state_address: "5/0/1"
  - name: "Chambre Auguste"
    address: "5/5/0"
    state_address: "5/5/1"
  - name: "Salle de bain"
    address: "6/0/0"
    state_address: "6/0/1"
  - name: "Patio extérieur"
    address: "4/7/0"
    state_address: "4/7/1"
  - name: "Prise commandée Salon baie"
    address: "13/1/1"
    state_address: "13/1/2"
  - name: "Eclairage Garage"
    address: "6/7/0"
    state_address: "6/7/1"

  # lumiere dimable

  - name: "Salon télé"
    address: "1/3/0"
    state_address: "1/3/1"
    brightness_address: "1/3/5"
    brightness_state_address: "1/3/3"
  - name: "Chambre parents"
    address: "5/3/0"
    state_address: "5/3/1"
    brightness_address: "5/3/2"
    brightness_state_address: "5/3/3"
  - name: "Salle à manger"
    address: "4/1/0"
    state_address: "4/1/1"
    brightness_address: "4/1/5"
    brightness_state_address: "4/1/3"
  - name: "Salle de bain  douche/baignoire"
    address: "6/1/0"
    state_address: "6/1/1"
    brightness_address: "6/1/5"
    brightness_state_address: "6/1/3"
  - name: "Salon"
    address: "4/2/0"
    state_address: "4/2/1"
    brightness_address: "4/2/5"
    brightness_state_address: "4/2/3"
  - name: "Salon piano"
    address: "4/0/0"
    state_address: "4/0/1"
    brightness_address: "4/0/5"
    brightness_state_address: "4/0/3"

  # Rubans LED
  - name: "Ruban LED Double hauteur"
    address: "6/4/0"
    state_address: "6/4/1"
    brightness_address: "6/4/2"
    brightness_state_address: "6/4/4"
    color_temperature_mode: "relative"
    color_temperature_address: "6/4/5"
    color_temperature_state_address: "6/4/6"
  - name: "Ruban LED salon"
    address: "6/2/0"
    state_address: "6/2/1"
    brightness_address: "6/2/2"
    brightness_state_address: "6/2/4"
    color_temperature_mode: "relative"
    color_temperature_address: "6/2/5"
    color_temperature_state_address: "6/2/6"
  - name: "Ruban LED salon piano"
    address: "6/3/0"
    state_address: "6/3/1"
    brightness_address: "6/3/2"
    brightness_state_address: "6/3/4"
    color_temperature_mode: "relative"
    color_temperature_address: "6/3/5"
    color_temperature_state_address: "6/3/6"

sensor:
  #alimentation KNX
  - name: "Courant du Bus"
    state_address: "0/2/0"
    type: current
  - name: "Tension du Bus"
    state_address: "0/3/0"
    type: voltage
  - name: "Utilisation du Bus"
    state_address: "0/4/2"
    type: percent
  - name: "Position porte de garage"
    state_address: "16/0/2"
    type: percent
  - name: "Temps de fonctionnement"
    state_address: "0/0/1"
    type: time_period_hrs
  - name: "Temps de fonctionnement depuis rédémarrage"
    state_address: "0/0/2"
    type: time_period_hrs
  - name: "Dernier évennement"
    state_address: "0/4/1"
    type: string
  #thermostat
  - name: "Température chambre Auguste"
    state_address: "9/1/0"
    type: temperature
  - name: "Température chambre Amis"
    state_address: "10/1/0"
    type: temperature
  - name: "Température chambre Parents"
    state_address: "3/1/0"
    type: temperature
  - name: "Température chambre Margaux"
    state_address: "8/1/0"
    type: temperature
  - name: "Température Salle d'eau"
    state_address: "7/1/0"
    type: temperature
  - name: "Température Salon Télé"
    state_address: "14/1/0"
    type: temperature
  - name: "Température Mur chauffant"
    state_address: "11/1/7"
    type: temperature
  - name: "Température SAlle de bain"
    state_address: "11/1/0"
    type: temperature
  #chaudiere
  - name: "Température H1 consigne"
    state_address: "17/0/5"
    type: temperature
  - name: "Température H1 actuelle"
    state_address: "17/0/6"
    type: temperature
  - name: "Température H2 consigne"
    state_address: "17/0/2"
    type: temperature
  - name: "Température H2 actuelle"
    state_address: "17/0/3"
    type: temperature
  - name: "Température extérieure issue chaudiere"
    state_address: "17/0/8"
    type: temperature
  - name: "Température ECS actuelle"
    state_address: "17/0/10"
    type: temperature
  - name: "Température ECS consigne"
    state_address: "17/0/9"
    type: temperature

  - name: "pourcentage de modulation chauffage"
    state_address: "17/0/12"
    type: percent

  - name: "pression eau chaudiere"
    state_address: "17/0/0"
    type: pressure_2byte

  - name: "pourcentage de chauffe Salle d'eau"
    state_address: "7/1/3"
    type: percent
  - name: "pourcentage de chauffe Salle de bain"
    state_address: "11/1/3"
    type: percent

  - name: "pourcentage de chauffe chambre Auguste"
    state_address: "9/1/3"
    type: percent
  - name: "pourcentage de chauffe chambre Margaux"
    state_address: "8/1/3"
    type: percent
  - name: "pourcentage de chauffe Chambre Patio"
    state_address: "10/1/3"
    type: percent
  - name: "pourcentage de chauffe Chambre parents"
    state_address: "3/1/3"
    type: percent

cover:
  - name: "Volet Buanderie"
    move_long_address: "2/0/0"
    stop_address: "2/0/1"
    position_address: "2/0/3"
    position_state_address: "2/0/2"
  #    travelling_time_down: "32"
  #   travelling_time_up: "32"
  - name: "Volet Salle de bain"
    move_long_address: "2/1/0"
    stop_address: "2/1/1"
    position_address: "2/1/3"
    position_state_address: "2/1/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Volet Salon télé"
    move_long_address: "2/2/0"
    stop_address: "2/2/1"
    position_address: "2/2/3"
    position_state_address: "2/2/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Volet Chambre Margaux"
    move_long_address: "2/3/0"
    stop_address: "2/3/1"
    position_address: "2/3/3"
    position_state_address: "2/3/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Volet Chambre Auguste"
    move_long_address: "2/4/0"
    stop_address: "2/4/1"
    position_address: "2/4/3"
    position_state_address: "2/4/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Volet Bureau"
    move_long_address: "2/5/0"
    stop_address: "2/5/1"
    position_address: "2/5/3"
    position_state_address: "2/5/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Volet Salle d'eau"
    move_long_address: "2/6/0"
    stop_address: "2/6/1"
    position_address: "2/6/3"
    position_state_address: "2/6/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Volet Chambre parentale"
    move_long_address: "2/7/0"
    stop_address: "2/7/1"
    position_address: "2/7/3"
    position_state_address: "2/7/2"
  #    travelling_time_down: "32"
  #    travelling_time_up: "32"
  - name: "Porte de garage"
    move_long_address: "16/0/0"
    stop_address: "16/0/1"
    position_address: "16/0/3"
    position_state_address: "16/0/2"

# Interrupteurs

switch:
  - name: "VMC coté rue"
    address: "12/0/0"
    state_address: "12/0/1"
  - name: "VMC coté jardi "
    address: "12/1/0"
    state_address: "12/1/1"
  - name: "Sirène Extérieure "
    address: "12/2/2"
    state_address: "12/2/3"
  - name: "Forcage Chauffage Salle d'eau"
    address: "12/4/0"
  - name: "Toutes lumières sauf enfants"
    address: "6/6/0"
  - name: "Blocage Porte de garage"
    address: "16/0/8"
  #Chaudiere
  - name: "switch H1"
    address: "17/1/0"
  - name: "Switch H2"
    address: "17/1/2"
  - name: "Switch ECS"
    address: "17/1/3"
  - name: "Switch Mode été"
    address: "17/1/1"
  - name: "Switch Pompe bouclage ECS"
    address: "17/2/0"
    state_address: "17/2/1"

climate:
  - name: "thermostat Salle d'eau"
    temperature_address: "7/1/0"
    setpoint_shift_address: "7/0/4"
    setpoint_shift_state_address: "7/1/5"
    target_temperature_state_address: "7/1/1"
    operation_mode_address: "7/0/5"
    operation_mode_state_address: "7/1/4"
  - name: "thermostat Salle de bain"
    temperature_address: "11/1/0"
    setpoint_shift_address: "11/0/4"
    setpoint_shift_state_address: "11/1/5"
    target_temperature_state_address: "11/1/1"
    operation_mode_address: "11/0/5"
    operation_mode_state_address: "11/1/4"
  - name: "thermostat chambre Parents"
    temperature_address: "3/1/0"
    setpoint_shift_address: "3/0/4"
    setpoint_shift_state_address: "3/1/5"
    target_temperature_state_address: "3/1/1"
    operation_mode_address: "3/0/5"
    operation_mode_state_address: "3/1/4"
  - name: "thermostat chambre Margaux"
    temperature_address: "8/1/0"
    setpoint_shift_address: "8/0/4"
    setpoint_shift_state_address: "8/1/5"
    target_temperature_state_address: "8/1/1"
    operation_mode_address: "8/0/5"
    operation_mode_state_address: "8/1/4"
  - name: "thermostat chambre Auguste"
    temperature_address: "9/1/0"
    setpoint_shift_address: "9/0/4"
    setpoint_shift_state_address: "9/1/5"
    target_temperature_state_address: "9/1/1"
    operation_mode_address: "9/0/5"
    operation_mode_state_address: "9/1/4"
  - name: "thermostat chambre amis"
    temperature_address: "10/1/0"
    setpoint_shift_address: "10/0/4"
    setpoint_shift_state_address: "10/1/5"
    target_temperature_state_address: "10/1/1"
    operation_mode_address: "10/0/5"
    operation_mode_state_address: "10/1/4"
