# Alarme / détection alarme Nuit
# entity_id : automation.declenchement_alarme_nuit
# Export Home Assistant du 2026-08-30 — ne pas éditer à la main sans réimport.
---
id: '1686494168795'
alias: Alarme / détection alarme Nuit
description: ''
triggers:
- entity_id:
  - binary_sensor.capteur_cuisine
  from: 'off'
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.capteur_salon_piano
  from: 'off'
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.capteur_patio
  from: 'off'
  to: 'on'
  trigger: state
- entity_id:
  - binary_sensor.capteur_garage
  from: 'off'
  to: 'on'
  trigger: state
conditions:
- condition: state
  entity_id: alarm_control_panel.alarme_maison
  state: armed_night
actions:
- target:
    entity_id: alarm_control_panel.alarme_maison
  data: {}
  action: alarm_control_panel.alarm_trigger
- action: notify.mobile_app_pixel_9a
  data: {}
mode: single
