# Garage / Allumage lumière garage automatique
# entity_id : automation.allumage_lumiere_garage_automatique_2
# Export Home Assistant du 2026-08-30 — ne pas éditer à la main sans réimport.
---
id: '1701509636678'
alias: Garage / Allumage lumière garage automatique
description: 'Sur détection capteur '
mode: single
triggers:
- entity_id:
  - binary_sensor.capteur_garage
  from: 'off'
  to: 'on'
  trigger: state
actions:
- service: light.turn_on
  data: {}
  target:
    entity_id: light.eclairage_garage
conditions: []
