# Sonette quand qqn sonne
# entity_id : automation.sonette_quand_qqn_sonne
# Export Home Assistant du 2026-09-02 — ne pas éditer à la main sans réimport.
---
id: '1681055973731'
alias: Sonette quand qqn sonne
description: ''
triggers:
- entity_id:
  - binary_sensor.interphone_visitor
  from: 'off'
  to: 'on'
  trigger: state
conditions: []
actions:
- alias: Notification aux telephones actives
  action: script.alerte_famille
  data:
    title: Sonnette maison
    message: Quelqu'un sonne !
- data:
    with_group: true
    entity_id: media_player.salle_a_manger
  action: sonos.snapshot
- alias: Reglage volume en fonction de l'heure
  if:
  - condition: time
    after: '21:00:00'
    before: 08:00:00
  then:
  - data:
      volume_level: 0.1
    target:
      entity_id: media_player.salle_a_manger
    action: media_player.volume_set
  else:
  - data:
      volume_level: 0.35
    target:
      entity_id: media_player.salle_a_manger
    action: media_player.volume_set
- data:
    media:
      media_content_id: https://www.soundjay.com/door/doorbell-1.mp3
      media_content_type: music
      metadata: {}
  target:
    entity_id:
    - media_player.salle_a_manger
  action: media_player.play_media
- delay:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
- data:
    media:
      media_content_id: https://www.soundjay.com/door/doorbell-1.mp3
      media_content_type: music
      metadata: {}
  target:
    entity_id:
    - media_player.salle_a_manger
  action: media_player.play_media
- data:
    with_group: true
    entity_id: media_player.salle_a_manger
  action: sonos.restore
mode: single
